# ===================================
# Filter Scope Definitions
# ===================================

scopes:

    brand:
        label: Brand
        modelClass: Octommerce\Octommerce\Models\Brand
        nameFrom: name
        conditions: brand_id in (:filtered)

    category:
        label: Category
        modelClass: Octommerce\Octommerce\Models\Category
        nameFrom: name
        scope: FilterCategories

    list:
        label: List
        modelClass: Octommerce\Octommerce\Models\ProductList
        nameFrom: name
        scope: FilterLists

    published:
        label: Published?
        type: switch
        conditions:
            - is_published <> 1
            - is_published = 1

    available:
        label: Only available products
        type: checkbox
        scope: available