phone:
    label: Phone Number
    span: auto
    type: text
    tab: rainlab.user::lang.user.account
address:
    label: Primary Address
    type: textarea
    span: auto
    tab: Location
postcode:
    label: Post Code
    type: text
    span: auto
    tab: Location
state:
    label: State
    type: relation
    dependsOn: country
    span: auto
    tab: Location
city:
    label: City
    type: relation
    dependsOn: state
    span: auto
    tab: Location
orders:
    type: partial
    path: $/octommerce/octommerce/controllers/users/_order_history.htm
    tab: Order History
